### ISSUE TITLE
Build fails with NoSuchFieldError: EOF_TOKEN

### ISSUE THREAD

**Issue by dr0i** [hbz/rpb#24]
Since  [metafix 0.4.0-SNAPSHOT uses rc versions of metafacture-core](https://github.com/metafacture/metafacture-fix/pull/266/commits/71da106651f871ed8fea4dbfd579c94303ad04aa) the build fails with:
> org.metafacture.commons.reflection.ReflectionException: class could not be instantiated: class org.metafacture.metafix.Metafix
[...]
Caused by: java.lang.NoSuchFieldError: EOF_TOKEN

Relates to https://github.com/metafacture/metafacture-fix/pull/266.

**Comment by fsteeg** [comment]
It seems the actually reproducible problem is the resolution of the metafacture-core RC dependency itself  (I don't get the ` java.lang.NoSuchFieldError: EOF_TOKEN`). It's the error both in [the GitHub Action](https://github.com/hbz/rpb/actions/runs/3541861780/jobs/5946652810#step:5:2030) and also what I get locally (even when not explicitly depending on the RC): `sbt.ResolveException: unresolved dependency: org.metafacture#metafacture-flowcontrol;metafacture-core-5.4.1-rc3: not found`.

As far as I understand, the root problem is that since the switch to the RC (which is published on GitHub Packages, not Central) Fix now has a transitive dependency that can only be resolved from GitHub Packages. There seems to be an [sbt plugin](https://index.scala-lang.org/djspiewak/sbt-github-packages), but not for our versions of sbt and Scala.

**Comment by dr0i** [comment]
What did you not like about https://github.com/hbz/rpb/commit/e4f76b3145d1ff0cd8ec7610840726486009efa3 ? It seems to me more future proof, as it uses newer mf dependencies.

**Comment by dr0i** [comment]
Ah - you also commented at https://github.com/hbz/rpb/pull/25#issuecomment-1330657960 which I saw too late.
